### ISSUE TITLE
Fitur Pantau Ujian

### ISSUE THREAD

**Issue by linmug76** [almazary/new_elearning#10]
Saat siswa kehabisan waktu mengerjakan, maka tugas nya nyantol di pantau ujian. Sedangkan soal  sdh kami tutup dan dibuka kembali hari berikutnya.
Efeknya siswa tdk bisa lanjut ke soal berikutnya karena nyantol disoal sebelumnya. (Sehari 2 mapel).
Utk itu kami berharap ada tombol Proses ujian, disebelah tombol reset dan lihat jawaban sementara. Fungsi tombol proses spy tugas siswa bisa dimasukkan saat itu juga tanpa harus menerbitkan soal.
Terimakasih byk atas perhatiannya🙏
![IMG_20201201_051434](https://user-images.githubusercontent.com/75281135/100673787-aa49b400-3396-11eb-9a1a-7d4f3288d70c.png)

**Comment by almazary** [comment]
Silakan update file application/core/MY_Controller.php dengan ini https://raw.githubusercontent.com/almazary/new_elearning/master/application/core/MY_Controller.php untuk menanggulangi siswa yang nyantol.

**Comment by linmug76** [comment]
Alhamdulillah terimakasih mas Ary, segera kami update

**Comment by linmug76** [comment]
Terimakasih Mas Ary, akan segera kami coba. Barokallah

Pada tanggal Jum, 7 Mei 2021 15:52, Almazari ***@***.***>
menulis:
