### ISSUE TITLE
undefined variable $login_receiver

### ISSUE THREAD

**Issue by ariews** [almazary/new_elearning#2]
Jika kondisi di baris 174

https://github.com/almazary/new_elearning/blob/1c750516a735cafb4b23dbda8da599227d2c5d8e/application/controllers/message.php#L174

tidak terpenuhi, maka variable $login_receiver di baris 185 tidak terdefinisi

https://github.com/almazary/new_elearning/blob/1c750516a735cafb4b23dbda8da599227d2c5d8e/application/controllers/message.php#L185

**Comment by almazary** [comment]
Oh iya betul mas @ariews 
Segera diperbaiki...
