### ISSUE TITLE
ckeditor problem

### ISSUE THREAD

**Issue by Yudas1337** [almazary/new_elearning#9]
ini ada error untuk ckeditor nya mas , dijalankan pada local dan juga hosting tidak bisa sehingga textarea untuk mengisi soal tidak muncul . 

error console.log : 
![error1](https://user-images.githubusercontent.com/49679669/100584431-b09c4980-331e-11eb-856f-1ec65956043e.png)

Uncaught SyntaxError: Unexpected token '<'
    at plugin.js?t=G87E:50
ckeditor.js:237 Uncaught TypeError: Cannot read property 'icons' of null
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:237)
    at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:236)
    at e (ckeditor.js:231)
    at Array.A (ckeditor.js:231)
    at r (ckeditor.js:231)
    at ckeditor.js:232

**Comment by almazary** [comment]
ini karena versi phpnya ketinggian mas, coba maksimal versi 7.3, minimal 5.6

**Comment by Yudas1337** [comment]
terimakasih banyak atas responnya mas , nanti akan saya coba kembali

**Comment by Yudas1337** [comment]
solved menggunakan php versi 7.3, terimakasih banyak mas.
